import type { NextPage } from "next";
import Head from "next/head";
import ExamsFooter from "@exams/ExamsFooter";
import AllBlogs from "@blogs/Blogs";
import { _request } from "src/utils/request.util";

const Blogs: NextPage = (props: any) => {
  const blogs = props.blogs;
  return (
    <>
      <Head>
        <title>Blogs | TestKart</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AllBlogs blogs={blogs} />
      {/* <ExamsFooter /> */}
    </>
  );
};

export default Blogs;

export async function getServerSideProps() {
  const res = await _request("get", `app/blogs`);

  if (res?.success) {
    return {
      props: {
        blogs: res.data,
      },
    };
  } else {
    return {
      props: {
        data: "Error",
      },
    };
  }
}
