import type { NextPage } from "next";
import Head from "next/head";
import Exams from "@home/Exams";
import Hero from "@home/Hero";
import HomePopularSeries from "@home/HomePopularSeries";
import Testimonials from "@components/testimonials/Testimonials";
import StudentLogin from "@student/auth/StudentLogin";

const Student: NextPage = () => {
  return (
    <>
      <Head>
        <title>Student | TestKart</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* <Hero /> */}
      <StudentLogin/>
      {/* <Exams exams={undefined} />
      <HomePopularSeries />
      <Testimonials /> */}
    </>
  );
};

export default Student;
